routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\Login;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TestimonialsController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AppointmentsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminServicesController;
use Illuminate\Http\Request;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\Authenticate;

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/home',[PostsController::class, 'home'])->name('home');
    Route::get('/admin/posts/',[PostsController::class, 'index'])->name('posts.index');
    Route::get('/admin/posts/create', [PostsController::class, 'create'])->name('posts.create');
    Route::post('/admin/posts', [PostsController::class, 'store'])->name('posts.store');
    Route::get('/admin/posts/{id}/edit', [PostsController::class, 'edit'])->name('posts.edit');
    Route::put('/admin/posts/{id}', [PostsController::class, 'update'])->name('posts.update');
    Route::delete('/admin/posts/{id}', [PostsController::class, 'destroy'])->name('posts.destroy');
});

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/admin',[DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/google/analytics/authorize',[DashboardController::class, 'authorize']);

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/testimonials', [TestimonialsController::class, 'index'])->name('testimonials.index');
    Route::get('/admin/testimonials/create', [TestimonialsController::class, 'create'])->name('testimonials.create');
    Route::post('/admin/testimonials', [TestimonialsController::class, 'store'])->name('testimonials.store');
    Route::get('/admin/testimonials/{id}/edit', [TestimonialsController::class, 'edit'])->name('testimonials.edit');
    Route::put('/admin/testimonials/{id}', [TestimonialsController::class, 'update'])->name('testimonials.update');
    Route::delete('/admin/testimonials/{id}', [TestimonialsController::class, 'destroy'])->name('testimonials.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/services', [ServicesController::class, 'index'])->name('services.index');
    Route::get('/admin/services/create', [ServicesController::class, 'create'])->name('services.create');
    Route::post('/admin/services', [ServicesController::class, 'store'])->name('services.store');
    Route::get('/admin/services/{id}/edit', [ServicesController::class, 'edit'])->name('services.edit');
    Route::put('/admin/services/{id}', [ServicesController::class, 'update'])->name('services.update');
    Route::delete('/admin/services/{id}', [ServicesController::class, 'destroy'])->name('services.destroy');
});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/categories', [CategoriesController::class, 'index'])->name('categories.index');
    Route::get('/admin/categories/create', [CategoriesController::class, 'create'])->name('categories.create');
    Route::post('/admin/categories', [CategoriesController::class, 'store'])->name('categories.store');
    Route::get('/admin/categories/{id}/edit', [CategoriesController::class, 'edit'])->name('categories.edit');
    Route::put('/admin/categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
    Route::delete('/admin/categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/appointments', [AppointmentsController::class, 'index'])->name('appointments.index');
    Route::put('/admin/appointments/{id}', [AppointmentsController::class, 'update'])->name('appointments.update');
    Route::delete('/admin/appointments/{id}', [AppointmentsController::class, 'destroy'])->name('appointments.destroy');
});
Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/profile/{id}/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/admin/profile/{id}', [ProfileController::class, 'update'])->name('profile.update');
});

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'home'])->name('index');
    Route::get('/portfolio', [PostsController::class, 'display'])->name('posts.index');
    Route::get('/show/{id}', [PostsController::class, 'show'])->name('show');
    Route::get('/services', [ServicesController::class, 'display'])->name('services.index');
    Route::get('/about', [AboutController::class, 'index'])->name('about');
    Route::get('/contact', [AppointmentsController::class, 'contact'])->name('contact');
    Route::post('/contact', [AppointmentsController::class, 'store'])->name('contact.store');
    Route::get('/gallery/{categoryId?}', [GalleryController::class, 'index'])->name('gallery.index');
    Route::get('emails/contact/{id}', [AppointmentsController::class, 'display']);
});









Auth::routes();

app/Models/Services.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Services extends Model
{
    protected $table = 'services';

    protected $fillable = [
        'name', 'description','price'
    ];


}

app/Http/Controllers/ServicesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Services;
use App\Models\Testimonials;


class ServicesController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware(['web','auth', 'authcheck']);
    // }

    public function display()
    {
        $services = Services::all();
        $testimonials = Testimonials::all();
        return view('services', ['services' => $services, 'testimonials' => $testimonials]);
    }

    public function index()
    {
        $services = Services::all();
        return view('admin.services.index', ['services' => $services]);
    }

    public function create()
    {
        return view('admin.services.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'description' => 'required',
            'price' => 'required|numeric'
        ]);
        $service = new Services();
        $service->name = $validatedData['name'];
        $service->description = $validatedData['description'];
        $service->price = $validatedData['price'];

        if($service->save()) {
            return back()->with('success', 'Service created successfully');
        } else {
            return back()->withErrors(['error', 'Unable to create service']);
        }

    }

    public function edit($id)
    {
        $service = Services::findOrFail($id);
        return view('admin.services.edit', ['service' => $service]);
    }

    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'description' => 'required',
            'price' => 'required|numeric'
        ]);
        $service = Services::findOrFail($id);
        $service->name = $validatedData['name'];
        $service->description = $validatedData['description'];
        $service->price = $validatedData['price'];
        if($service->save()) {
            return back()->with('success', 'Service updated successfully');
        } else {
            return back()->withErrors(['error', 'Unable to create service']);
        }
    }

    public function destroy($id)
    {
        $service = Services::findOrFail($id);
        $service->delete();
        return back()->with('success', 'Service deleted successfully');
    }
}

resources/views/admin/services/create.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Service Upload</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form class="container-centered" method="POST" action=" {{ route('admin.services.store')}}" enctype="multipart/form-data">
                        @csrf

                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Name</label>
                             <input type="text" class="form-control" name="name"/>
                         </div>

                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Description</label>
                             <textarea class="form-control" rows="3" name="description"></textarea>
                         </div>

                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Start Price/label>
                             <input type="text" class="form-control" name="price"/>
                         </div>

                         <button type="submit" class="btn btn-primary mb-2 mt-2 hover:bg-indigo-700">Submit</button>
                     </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/services/edit.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


                <h2>Service Update</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form method="POST" action="{{ route('admin.services.update', ['id' => $service->id])}}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">


                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Name</label>
                             <input type="text" class="form-control" name="name" value="{{ $service->name }}"/>
                         </div>

                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Description</label>
                             <textarea class="form-control" rows="3" name="description">{{ $service->description }}</textarea>
                         </div>


                         <div class="form-group mb-2">
                            <label class="form-label" for="project-title">Start Price</label>
                            <input type="text" class="form-control" name="price" value="{{ $service->price }}"/>
                        </div>

                        <button type="submit" class="btn btn-primary mb-2 hover:bg-indigo-700">Submit</button>
                    </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/services/index.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Services</h2>
              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row mb-2">
                <div class="col-md-3 offset-md-9">
                    <a href="{{ route('admin.services.create') }}">
                        <button type="button" class="btn btn-sm btn-primary float-right">
                           <i class="fa fa-plus text-white"></i> Add Service
                         </button>
                    </a>
                </div>
            </div>
             <table class="table table-responsive-lg table-responsive-md table-responsive-sm">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($services as $service)
                    <tr>
                        <td>
                            {{ $service->name }}
                        </td>
                        <td>{{ $service->description }}</td>
                        <td>{{ $service->price }}</td>
                        <td>
                            <a href="{{route('admin.services.edit', $service->id)}}">
                                <i class="fa fa-edit text-primary"></i>
                            </a>
                            <span>
                                <form action="{{ route('admin.services.destroy', $service->id) }}" method="POST" class="form-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" name="delete" onclick="
                                        event.preventDefault();
                                        Swal.fire({
                                            title: 'Are you sure?',
                                            text: 'You will not be able to recover this service!',
                                            icon: 'warning',
                                            showCancelButton: true,
                                            confirmButtonText: 'Yes, delete it!',
                                            cancelButtonText: 'No, keep it'
                                        }).then((result) => {
                                            if (result.value) {
                                                this.closest('form').submit();
                                            }
                                        });
                                    ">
                                        <i class="fa fa-trash text-danger"></i>
                                    </button>
                                </form>

                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
             </table>
          </div>
        </section>


      </main><!-- End #main -->
</x-main>