routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\Login;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TestimonialsController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AppointmentsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminServicesController;
use Illuminate\Http\Request;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\Authenticate;

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/home',[PostsController::class, 'home'])->name('home');
    Route::get('/admin/posts/',[PostsController::class, 'index'])->name('posts.index');
    Route::get('/admin/posts/create', [PostsController::class, 'create'])->name('posts.create');
    Route::post('/admin/posts', [PostsController::class, 'store'])->name('posts.store');
    Route::get('/admin/posts/{id}/edit', [PostsController::class, 'edit'])->name('posts.edit');
    Route::put('/admin/posts/{id}', [PostsController::class, 'update'])->name('posts.update');
    Route::delete('/admin/posts/{id}', [PostsController::class, 'destroy'])->name('posts.destroy');
});

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/admin',[DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/google/analytics/authorize',[DashboardController::class, 'authorize']);

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/testimonials', [TestimonialsController::class, 'index'])->name('testimonials.index');
    Route::get('/admin/testimonials/create', [TestimonialsController::class, 'create'])->name('testimonials.create');
    Route::post('/admin/testimonials', [TestimonialsController::class, 'store'])->name('testimonials.store');
    Route::get('/admin/testimonials/{id}/edit', [TestimonialsController::class, 'edit'])->name('testimonials.edit');
    Route::put('/admin/testimonials/{id}', [TestimonialsController::class, 'update'])->name('testimonials.update');
    Route::delete('/admin/testimonials/{id}', [TestimonialsController::class, 'destroy'])->name('testimonials.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/services', [ServicesController::class, 'index'])->name('services.index');
    Route::get('/admin/services/create', [ServicesController::class, 'create'])->name('services.create');
    Route::post('/admin/services', [ServicesController::class, 'store'])->name('services.store');
    Route::get('/admin/services/{id}/edit', [ServicesController::class, 'edit'])->name('services.edit');
    Route::put('/admin/services/{id}', [ServicesController::class, 'update'])->name('services.update');
    Route::delete('/admin/services/{id}', [ServicesController::class, 'destroy'])->name('services.destroy');
});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/categories', [CategoriesController::class, 'index'])->name('categories.index');
    Route::get('/admin/categories/create', [CategoriesController::class, 'create'])->name('categories.create');
    Route::post('/admin/categories', [CategoriesController::class, 'store'])->name('categories.store');
    Route::get('/admin/categories/{id}/edit', [CategoriesController::class, 'edit'])->name('categories.edit');
    Route::put('/admin/categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
    Route::delete('/admin/categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/appointments', [AppointmentsController::class, 'index'])->name('appointments.index');
    Route::put('/admin/appointments/{id}', [AppointmentsController::class, 'update'])->name('appointments.update');
    Route::delete('/admin/appointments/{id}', [AppointmentsController::class, 'destroy'])->name('appointments.destroy');
});
Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/profile/{id}/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/admin/profile/{id}', [ProfileController::class, 'update'])->name('profile.update');
});

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'home'])->name('index');
    Route::get('/portfolio', [PostsController::class, 'display'])->name('posts.index');
    Route::get('/show/{id}', [PostsController::class, 'show'])->name('show');
    Route::get('/services', [ServicesController::class, 'display'])->name('services.index');
    Route::get('/about', [AboutController::class, 'index'])->name('about');
    Route::get('/contact', [AppointmentsController::class, 'contact'])->name('contact');
    Route::post('/contact', [AppointmentsController::class, 'store'])->name('contact.store');
    Route::get('/gallery/{categoryId?}', [GalleryController::class, 'index'])->name('gallery.index');
    Route::get('emails/contact/{id}', [AppointmentsController::class, 'display']);
});









Auth::routes();

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Media;
use App\Models\Category;
use App\Models\Testimonials;




class Posts extends Model
{
    protected $table = 'posts';

    protected $fillable = [
        'category_id', 'title', 'description', 'project_date', 'project_url', 'client_name', 'designer'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function testimonials() {
        return $this->hasMany(Testimonials::class, 'posts_id');
    }

    public function media()
    {
        return $this->hasMany(Media::class,  'posts_id', 'id');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;
use App\Models\Posts;
use App\Models\Media;
use App\Models\Category;
use App\Models\Testimonials;
use Illuminate\Http\Request;
use App\Http\Requests\PostCreateRequest;
use App\Http\Requests\PostEditRequest;
use Illuminate\Support\Facades\Storage;


class PostsController extends Controller
{

    public function home()
    {
        $posts = Posts::with('media')->get();
        return view('admin.home', compact('posts'));
    }

    public function display()
{
    $categories = Category::all();
    $posts = Posts::with('media', 'category')->get();
    return view('portfolio', compact('posts', 'categories'));
}



    public function show($id)
    {
        $post = Posts::with('media','testimonials','category')->findOrFail($id);
        $categoryName= $post->category->name;
        return view('portfolio-details', compact('post', 'categoryName'));
    }

    public function index()
    {
        $posts = Posts::where('is_deleted', 0)->get();
        return view('admin.posts.index', ['posts' => $posts]);
    }


    public function create()
    {
        $categories = Category::All();
        return view('admin.posts.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'project_date' => 'required|date',
            'description' => 'required',
            'category_id' => 'required|numeric',
            'client_name' => 'required|max:255',
            'designer' => 'required|max:255',
        ]);

        $post = new Posts();
        $post->title = $validatedData['title'];
        $post->project_date = $validatedData['project_date'];
        $post->description = $validatedData['description'];
        $post->category_id = $validatedData['category_id'];
        $post->client_name = $validatedData['client_name'];
        $post->designer = $validatedData['designer'];

        if ($post->save()) {
            $postId = $post->id;

            if ($request->hasFile('media')) {
                $files = $request->all()['media'];

                foreach ($files as $file) {
                    $extension = $file->getClientOriginalExtension();
                    $type = '';
                    if ($extension === 'jpg' || $extension === 'jpeg' || $extension === 'png') {
                        $type = 'image';
                        $path = $file->move(public_path('assets/uploads/images'), $file->getClientOriginalName());
                    } else if ($extension === 'mp4' || $extension === 'avi') {
                        $type = 'video';
                        $path = $file->move(public_path('assets/uploads/videos'), $file->getClientOriginalName());
                    } else if ($extension === 'mp3' || $extension === 'wav') {
                        $type = 'audio';
                        $path = $file->move(public_path('assets/uploads/audios'), $file->getClientOriginalName());
                    }

                    $media = new Media();
                    $media->media = $file->getClientOriginalName();
                    $media->type = $type;
                    $media->posts_id = $postId;
                    if (!$media->save()) {
                        return back()->with('error', 'Media was not saved');
                    }
                }
            }
            return back()->with('success', 'Post created successfully.');
        } else {
            return back()->with('error', 'Post was not saved');
        }
    }


    public function update(PostEditRequest $request, $id)
    {
        $validatedData = $request->validated();
        $post = Posts::findOrFail($id);

        if ($request->hasFile('media')) {
            $files = $request->file('media');
            $existingFiles = Media::where('posts_id', $id)->get();

            foreach ($files as $file) {
                $extension = $file->getClientOriginalExtension();
                $type = '';
                if ($extension === 'jpg' || $extension === 'jpeg' || $extension === 'png') {
                    $type = 'image';
                    $path = $file->move(public_path('assets/uploads/images'), $file->getClientOriginalName());
                } else if ($extension === 'mp4' || $extension === 'avi') {
                    $type = 'video';
                    $path = $file->move(public_path('assets/uploads/videos'), $file->getClientOriginalName());
                } else if ($extension === 'mp3' || $extension === 'wav') {
                    $type = 'audio';
                    $path = $file->move(public_path('assets/uploads/audios'), $file->getClientOriginalName());
                }

                if ($existingFiles->count() > 0) {
                    $existingFiles->each(function ($existingFile) use ($post) {
                        $existingFile->delete();
                    });
                }

                $fileData = [
                    'posts_id' => $post->id,
                    'media' => $file->getClientOriginalName(),
                    'type' => $type,
                ];
                Media::create($fileData);
            }
        }

        if (!$post->update($validatedData)) {
            return back()->withErrors(['Error updating post']);
        }

        return back()->with('success', 'Post has been updated successfully!');
    }


    public function edit($id)
    {
        $post = Posts::find($id);
        $categories = Category::All();
        return view('admin.posts.edit', compact('post', 'categories'));
    }

    public function destroy($id)
    {
        $post = Posts::findOrFail($id);
        $post->is_deleted = 1;
        $post->save();
        return back()->with('success', 'Post deleted successfully');
    }
}

resources/views/admin/posts/create.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Project Upload</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->
        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form class="container-centered"  method="POST" action="{{ route('admin.posts.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group mb-2">
                            <label class="form-label" for="project-title">Select Photo/Video</label>
                            <input type="file" name="media[]" class="form-control"  multiple >
                        </div>

                        <div class="form-group mb-2">
                            <label class="form-label" for="project-title">Project Title</label>
                            <input type="text" class="form-control" name="title"/>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="project-title">Project Date</label>
                            <input type="date" class="form-control" name="project_date"/>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Project Description</label>
                            <textarea class="form-control" rows="3" name="description"></textarea>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Project Category</label>
                            <select class="form-control" name="category_id">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Client Name</label>
                            <input type="text" class="form-control" name="client_name"/>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Designer</label>
                            <input type="text" class="form-control" name="designer"/>
                        </div>
                        <button type="submit" class="btn btn-primary mb-2 mt-2 hover:bg-indigo-700">Submit</button>
                    </form>

                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/posts/edit.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


                <h2>Project Update</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form method="POST" action="{{ route('admin.posts.update', ['id' => $post->id])}}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <div class="form-group mb-2">
                            <label class="form-label" for="project-title">Select Photo/Video</label>
                            <input type="file" name="media[]" class="form-control"  multiple >
                        </div>
                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Project Title</label>
                             <input type="text" class="form-control" name="title" value="{{ $post->title }}"/>
                         </div>
                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Project Date</label>
                             <input type="date" class="form-control" name="project_date" value="{{ $post->project_date }}"/>
                         </div>
                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Project Description</label>
                             <textarea class="form-control" rows="3" name="description">{{ $post->description }}</textarea>
                         </div>
                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Project Category</label>
                             <select class="form-control" name="category_id">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id === $post->category_id ? 'selected' : '' }}>{{ $category->name }}</option>
                                @endforeach
                            </select>
                         </div>


                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Client Name</label>
                            <input type="text" class="form-control" name="client_name" value="{{ $post->client_name }}"/>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-label" for="customFile">Designer</label>
                            <input type="text" class="form-control" name="designer" value="{{ $post->designer }}"/>
                        </div>

                        <button type="submit" class="btn btn-primary mb-2 hover:bg-indigo-700">Submit</button>
                    </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/posts/index.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                @endif
                <h2>All Projects</h2>
              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row mb-2">
                <div class="col-md-2 offset-md-10">
                    <a href="{{ route('admin.posts.create') }}">
                        <button type="button" class="btn btn-sm btn-primary float-right w-150">
                           <i class="fa fa-plus text-white"></i> Add Project
                         </button>
                    </a>
                </div>
            </div>
             <table class="table table-responsive-md  table-responsive-lg table-responsive-sm">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Project Date</th>
                        <th>Client Name</th>
                        <th>Designer</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                    <tr>
                        <td>{{ $post->title }}</td>
                        <td>{{ date('jS M Y', strtotime( $post->project_date)) }}</td>
                        <td>{{ $post->client_name }}</td>
                        <td>{{ $post->designer }}</td>
                        <td>
                            <a href="{{route('admin.posts.edit', $post->id)}}">
                                <i class="fa fa-edit text-primary"></i>
                            </a>
                            <span>
                                <form action="{{ route('admin.posts.destroy', $post->id) }}" method="POST" class="form-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" onclick="
                                    event.preventDefault();
                                    Swal.fire({
                                        title: 'Are you sure?',
                                        text: 'You will not be able to recover this post!',
                                        icon: 'warning',
                                        showCancelButton: true,
                                        confirmButtonText: 'Yes, delete it!',
                                        cancelButtonText: 'No, keep it'
                                    }).then((result) => {
                                        if (result.value) {
                                            this.closest('form').submit();
                                        }
                                    });
                                ">
                                    <i class="fa fa-trash text-danger"></i>
                                </button>
                                </form>
                            </span>
                        </td>



                    </tr>
                    @endforeach
                </tbody>
             </table>
          </div>
        </section>


      </main><!-- End #main -->
</x-main>