routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\Login;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TestimonialsController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AppointmentsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminServicesController;
use Illuminate\Http\Request;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\Authenticate;

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/home',[PostsController::class, 'home'])->name('home');
    Route::get('/admin/posts/',[PostsController::class, 'index'])->name('posts.index');
    Route::get('/admin/posts/create', [PostsController::class, 'create'])->name('posts.create');
    Route::post('/admin/posts', [PostsController::class, 'store'])->name('posts.store');
    Route::get('/admin/posts/{id}/edit', [PostsController::class, 'edit'])->name('posts.edit');
    Route::put('/admin/posts/{id}', [PostsController::class, 'update'])->name('posts.update');
    Route::delete('/admin/posts/{id}', [PostsController::class, 'destroy'])->name('posts.destroy');
});

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/admin',[DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/google/analytics/authorize',[DashboardController::class, 'authorize']);

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/testimonials', [TestimonialsController::class, 'index'])->name('testimonials.index');
    Route::get('/admin/testimonials/create', [TestimonialsController::class, 'create'])->name('testimonials.create');
    Route::post('/admin/testimonials', [TestimonialsController::class, 'store'])->name('testimonials.store');
    Route::get('/admin/testimonials/{id}/edit', [TestimonialsController::class, 'edit'])->name('testimonials.edit');
    Route::put('/admin/testimonials/{id}', [TestimonialsController::class, 'update'])->name('testimonials.update');
    Route::delete('/admin/testimonials/{id}', [TestimonialsController::class, 'destroy'])->name('testimonials.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/services', [ServicesController::class, 'index'])->name('services.index');
    Route::get('/admin/services/create', [ServicesController::class, 'create'])->name('services.create');
    Route::post('/admin/services', [ServicesController::class, 'store'])->name('services.store');
    Route::get('/admin/services/{id}/edit', [ServicesController::class, 'edit'])->name('services.edit');
    Route::put('/admin/services/{id}', [ServicesController::class, 'update'])->name('services.update');
    Route::delete('/admin/services/{id}', [ServicesController::class, 'destroy'])->name('services.destroy');
});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/categories', [CategoriesController::class, 'index'])->name('categories.index');
    Route::get('/admin/categories/create', [CategoriesController::class, 'create'])->name('categories.create');
    Route::post('/admin/categories', [CategoriesController::class, 'store'])->name('categories.store');
    Route::get('/admin/categories/{id}/edit', [CategoriesController::class, 'edit'])->name('categories.edit');
    Route::put('/admin/categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
    Route::delete('/admin/categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/appointments', [AppointmentsController::class, 'index'])->name('appointments.index');
    Route::put('/admin/appointments/{id}', [AppointmentsController::class, 'update'])->name('appointments.update');
    Route::delete('/admin/appointments/{id}', [AppointmentsController::class, 'destroy'])->name('appointments.destroy');
});
Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/profile/{id}/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/admin/profile/{id}', [ProfileController::class, 'update'])->name('profile.update');
});

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'home'])->name('index');
    Route::get('/portfolio', [PostsController::class, 'display'])->name('posts.index');
    Route::get('/show/{id}', [PostsController::class, 'show'])->name('show');
    Route::get('/services', [ServicesController::class, 'display'])->name('services.index');
    Route::get('/about', [AboutController::class, 'index'])->name('about');
    Route::get('/contact', [AppointmentsController::class, 'contact'])->name('contact');
    Route::post('/contact', [AppointmentsController::class, 'store'])->name('contact.store');
    Route::get('/gallery/{categoryId?}', [GalleryController::class, 'index'])->name('gallery.index');
    Route::get('emails/contact/{id}', [AppointmentsController::class, 'display']);
});









Auth::routes();

app/Models/Testimonials.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Testimonials extends Model
{
    protected $table = 'testimonials';

    protected $fillable = [
        'name', 'designation', 'message', 'image','post_id'
    ];

    public function post() {
        return $this->belongsTo(Post::class, 'posts_id');
    }

}

app/Http/Controllers/TestimonialsController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Storage;
use App\Models\Testimonials;
use App\Models\Category;
use App\Models\Posts;
use Illuminate\Http\Request;
use App\Http\Requests\TestimonialCreateRequest;
use App\Http\Requests\TestimonialUpdateRequest;
class TestimonialsController extends Controller
{
    public function index()
    {
        $testimonials = Testimonials::where('is_deleted', 0)->get();
        return view('admin.testimonials.index', ['testimonials' => $testimonials]);
    }


    public function create()
    {
        $posts = Posts::all();
        return view('admin.testimonials.create', compact('posts'));
    }


    public function store(TestimonialCreateRequest $request)
    {
        $testimonial = new Testimonials();
        $testimonial->name = $request->input('name');
        $testimonial->message = $request->input('message');
        $testimonial->position = $request->input('position');
        $testimonial->posts_id = $request->input('posts_id');


        if($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = $image->getClientOriginalName();
            $path = $image->storeAs('public/assets/uploads/testimonials', $filename);
            // $destinationPath =$image->storeAs('public/assets/uploads/testimonials');
            $testimonial->image = $filename;
        }

        if($testimonial->save()) {
            return route('admin.testimonials.index')->with('success', 'Testimonial created successfully');
        } else {
            return back()->withErrors(['error', 'Unable to create testimonial']);
        }
    }

public function update(TestimonialUpdateRequest $request, $id)
{
    $testimonial = Testimonials::find($id);
    $testimonial->name = $request->input('name');
    $testimonial->message = $request->input('message');
    $testimonial->position = $request->input('position');
    $testimonial->posts_id = $request->input('posts_id');

    if ($request->hasFile('image')) {
        if ($testimonial->image) {
            $oldImagePath = storage_path('/app/public/assets/uploads/') . $testimonial->image;
            if (file_exists($oldImagePath)) {
                unlink($oldImagePath);
            }
        }

        $image = $request->file('image');
        $imageName = $image->getClientOriginalName();
        $destinationPath = storage_path('/app/public/assets/uploads');
        $image->move($destinationPath, $imageName);
        $testimonial->image = $imageName;
    }

    if($testimonial->save()) {
        return back()->with('success', 'Testimonial updated successfully');
    } else {
        return back()->withErrors(['error', 'Unable to update testimonial']);
    }
}



public function edit($id)
{
    $testimonial = Testimonials::find($id);
    $posts = Posts::all();
    return view('admin.testimonials.edit', compact('testimonial', 'posts'));
}


    public function destroy($id)
    {
        $testimonial = Testimonials::findOrFail($id);
        $testimonial->is_deleted = 1;
        $testimonial->save();
        return back()->with('success', 'Testimonial deleted successfully');

    }
}

resources/views/admin/testimonials/create.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Testimonial Upload</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form class="container-centered" method="POST" action=" {{ route('admin.testimonials.store')}}" enctype="multipart/form-data">
                        @csrf
                         <div class="row">
                            <div class="col-md-12 col-xl-3 col-lg-3 col-12 mt-2">
                                <div class="text-center">
                                    <div class="preview-container">
                                        <div id="preview-div" class="img-thumbnail">
                                        </div>
                                        <h6 class="mt-2 mb-2">Select testimonial Image</h6>
                                        <input type="file" name="image" class="form-control" onchange="previewImg(this)">
                                      </div>
                                  </div>

                              </div>

                              <div class="col-md-12 col-xl-9 col-lg-9 col-12 mt-2">
                                <div class="form-group mb-2">
                                    <label class="form-label" for="project-title">Name</label>
                                    <input type="text" class="form-control" name="name" />
                                </div>

                                <div class="form-group mb-2">
                                    <label class="form-label" for="customFile">Message</label>
                                    <textarea class="form-control" rows="3" name="message"></textarea>
                                </div>
                                <div class="form-group mb-2">
                                    <label class="form-label" for="customFile">Select Post for this Testimonials</label>
                                    <select class="form-control" name="posts_id">
                                       @foreach ($posts as $post)
                                           <option value="{{ $post->id }}" >{{ $post->title }}</option>
                                       @endforeach
                                   </select>
                                </div>

                                <div class="form-group mb-2">
                                   <label class="form-label" for="project-title">Position/Job Title</label>
                                   <input type="text" class="form-control" name="position" />
                               </div>
                              </div>
                        </div>

                        <div class="row mt-2">
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary mb-2 hover:bg-indigo-700">Submit</button>
                            </div>
                         </div>
                     </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/testimonials/edit.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


                <h2>Testimonial Update</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-8 col-sm-12 col-12">
                    <form method="POST" action="{{ route('admin.testimonials.update', ['id' => $testimonial->id])}}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <div class="row">
                            <div class="col-md-3">
                                <div class="text-center">
                                    <div class="preview-container">
                                        <div id="preview-div" class="img-thumbnail" style="background: url({{ $testimonial->image ? Storage::url('public/assets/uploads/testimonials/'.$testimonial->image) : asset('assets/img/avatar.jpg') }}); background-repeat: no-repeat; background-size: cover; height: 200px; width: 100%; border: 3px #fff; border-radius: 5%; ">
                                        </div>
                                        <h6 class="mt-2 mb-2">Change Image</h6>
                                        <input type="file" name="image" class="form-control" onchange="previewImg(this)">
                                      </div>
                                  </div>

                              </div>

                              <div class="col-md-9">
                                <div class="form-group mb-2">
                                    <label class="form-label" for="project-title">Name</label>
                                    <input type="text" class="form-control" name="name" value="{{ $testimonial->name }}"/>
                                </div>

                                <div class="form-group mb-2">
                                    <label class="form-label" for="customFile">Message</label>
                                    <textarea class="form-control" rows="3" name="message">{{ $testimonial->message }}</textarea>
                                </div>
                                <div class="form-group mb-2">
                                    <label class="form-label" for="customFile">Select Post for this Testimonials</label>
                                    <select class="form-control" name="posts_id">
                                       @foreach ($posts as $post)
                                           <option value="{{ $post->id }}" {{ $post->id === $testimonial->post_id ? 'selected' : '' }}>{{ $post->title }}</option>
                                       @endforeach
                                   </select>
                                </div>

                                <div class="form-group mb-2">
                                   <label class="form-label" for="project-title">Position/Job Title</label>
                                   <input type="text" class="form-control" name="position" value="{{ $testimonial->position }}"/>
                               </div>
                              </div>
                        </div>

                        <div class="row mt-2">
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary mb-2 hover:bg-indigo-700">Submit</button>
                            </div>
                         </div>

                    </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/testimonials/index.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Testimonials</h2>
              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row mb-2">
                <div class="col-md-3 offset-md-9">
                    <a href="{{ route('admin.testimonials.create') }}">
                        <button type="button" class="btn btn-sm btn-primary float-right">
                           <i class="fa fa-plus text-white"></i> Add Testimonial
                         </button>
                    </a>
                </div>
            </div>
             <table class="table table-responsive-lg table-responsive-md table-responsive-sm">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Message</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($testimonials as $testimonial)
                    <tr>
                        <td>
                            @if (!empty($testimonial))
                            <img src="{{ asset('assets/uploads/testimonials/'.$testimonial->image) }}" class="img-ls"  style="border-radius: 50%;" alt="">
                            @else
                                <img src="{{ asset('assets/img/avatar.jpg') }}" class="img-ls"  style="border-radius: 50%;" alt="">
                            @endif

                        </td>
                        <td>{{ $testimonial->name }}</td>
                        <td>{{ $testimonial->message }}</td>
                        <td>
                            <a href="{{route('admin.testimonials.edit', $testimonial->id)}}">
                                <i class="fa fa-edit text-primary"></i>
                            </a>
                            <span>
                                <form action="{{ route('admin.testimonials.destroy', $testimonial->id) }}" method="POST" class="form-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" name="delete" onclick="
                                        event.preventDefault();
                                        Swal.fire({
                                            title: 'Are you sure?',
                                            text: 'You will not be able to recover this testimonial!',
                                            icon: 'warning',
                                            showCancelButton: true,
                                            confirmButtonText: 'Yes, delete it!',
                                            cancelButtonText: 'No, keep it'
                                        }).then((result) => {
                                            if (result.value) {
                                                this.closest('form').submit();
                                            }
                                        });
                                    ">
                                        <i class="fa fa-trash text-danger"></i>
                                    </button>
                                </form>

                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
             </table>
          </div>
        </section>


      </main><!-- End #main -->
</x-main>