routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\Login;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TestimonialsController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AppointmentsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminServicesController;
use Illuminate\Http\Request;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\Authenticate;

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login']);
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/home',[PostsController::class, 'home'])->name('home');
    Route::get('/admin/posts/',[PostsController::class, 'index'])->name('posts.index');
    Route::get('/admin/posts/create', [PostsController::class, 'create'])->name('posts.create');
    Route::post('/admin/posts', [PostsController::class, 'store'])->name('posts.store');
    Route::get('/admin/posts/{id}/edit', [PostsController::class, 'edit'])->name('posts.edit');
    Route::put('/admin/posts/{id}', [PostsController::class, 'update'])->name('posts.update');
    Route::delete('/admin/posts/{id}', [PostsController::class, 'destroy'])->name('posts.destroy');
});

Route::middleware(['web','authcheck'])->group(function () {
    Route::get('/admin',[DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/google/analytics/authorize',[DashboardController::class, 'authorize']);

});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/testimonials', [TestimonialsController::class, 'index'])->name('testimonials.index');
    Route::get('/admin/testimonials/create', [TestimonialsController::class, 'create'])->name('testimonials.create');
    Route::post('/admin/testimonials', [TestimonialsController::class, 'store'])->name('testimonials.store');
    Route::get('/admin/testimonials/{id}/edit', [TestimonialsController::class, 'edit'])->name('testimonials.edit');
    Route::put('/admin/testimonials/{id}', [TestimonialsController::class, 'update'])->name('testimonials.update');
    Route::delete('/admin/testimonials/{id}', [TestimonialsController::class, 'destroy'])->name('testimonials.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/services', [ServicesController::class, 'index'])->name('services.index');
    Route::get('/admin/services/create', [ServicesController::class, 'create'])->name('services.create');
    Route::post('/admin/services', [ServicesController::class, 'store'])->name('services.store');
    Route::get('/admin/services/{id}/edit', [ServicesController::class, 'edit'])->name('services.edit');
    Route::put('/admin/services/{id}', [ServicesController::class, 'update'])->name('services.update');
    Route::delete('/admin/services/{id}', [ServicesController::class, 'destroy'])->name('services.destroy');
});


Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/categories', [CategoriesController::class, 'index'])->name('categories.index');
    Route::get('/admin/categories/create', [CategoriesController::class, 'create'])->name('categories.create');
    Route::post('/admin/categories', [CategoriesController::class, 'store'])->name('categories.store');
    Route::get('/admin/categories/{id}/edit', [CategoriesController::class, 'edit'])->name('categories.edit');
    Route::put('/admin/categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
    Route::delete('/admin/categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');
});

Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/appointments', [AppointmentsController::class, 'index'])->name('appointments.index');
    Route::put('/admin/appointments/{id}', [AppointmentsController::class, 'update'])->name('appointments.update');
    Route::delete('/admin/appointments/{id}', [AppointmentsController::class, 'destroy'])->name('appointments.destroy');
});
Route::middleware(['web','authcheck'])->name('admin.')->group(function () {
    Route::get('/admin/profile/{id}/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/admin/profile/{id}', [ProfileController::class, 'update'])->name('profile.update');
});

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'home'])->name('index');
    Route::get('/portfolio', [PostsController::class, 'display'])->name('posts.index');
    Route::get('/show/{id}', [PostsController::class, 'show'])->name('show');
    Route::get('/services', [ServicesController::class, 'display'])->name('services.index');
    Route::get('/about', [AboutController::class, 'index'])->name('about');
    Route::get('/contact', [AppointmentsController::class, 'contact'])->name('contact');
    Route::post('/contact', [AppointmentsController::class, 'store'])->name('contact.store');
    Route::get('/gallery/{categoryId?}', [GalleryController::class, 'index'])->name('gallery.index');
    Route::get('emails/contact/{id}', [AppointmentsController::class, 'display']);
});









Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
        'name', 'description',
    ];

    public function posts()
    {
        return $this->hasMany(Posts::class,  'posts_id', 'id');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', ['categories' => $categories]);
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'desc' => 'required',
        ]);
        $category = new Category();
        $category->name = $validatedData['name'];
        $category->desc = $validatedData['desc'];

        if($category->save()) {
            return back()->with('success', 'Category created successfully');
        } else {
            return back()->withErrors(['error', 'Unable to create category']);
        }
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.edit', ['category' => $category]);
    }

    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'desc' => 'required',
        ]);
        $category = Category::findOrFail($id);
        $category->name = $validatedData['name'];
        $category->desc = $validatedData['desc'];
        if($category->save()) {
            return back()->with('success', 'Category updated successfully');
        } else {
            return back()->withErrors(['error', 'Unable to update category']);
        }
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return back()->with('success', 'Category deleted successfully');
    }
}

resources/views/admin/categories/create.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Category Upload</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form class="container-centered" method="POST" action=" {{ route('admin.categories.store')}}" enctype="multipart/form-data">
                        @csrf

                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Name</label>
                             <input type="text" class="form-control" name="name"/>
                         </div>

                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Description</label>
                             <textarea class="form-control" rows="3" name="desc"></textarea>
                         </div>


                         <button type="submit" class="btn btn-primary mb-2 mt-2 hover:bg-indigo-700">Submit</button>
                     </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/categories/edit.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if (session('status'))
                <div id="alert" class="alert alert-success">
                  {{ session('status') }}
                </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


                <h2>Category Update</h2>

              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12 col-12">
                    <form method="POST" action="{{ route('admin.categories.update', ['id' => $category->id])}}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">


                         <div class="form-group mb-2">
                             <label class="form-label" for="project-title">Name</label>
                             <input type="text" class="form-control" name="name" value="{{ $category->name }}"/>
                         </div>

                         <div class="form-group mb-2">
                             <label class="form-label" for="customFile">Description</label>
                             <textarea class="form-control" rows="3" name="desc">{{ $category->desc }}</textarea>
                         </div>


                        <button type="submit" class="btn btn-primary mb-2 hover:bg-indigo-700">Submit</button>
                    </form>
                </div>
            </div>

          </div>
        </section>


      </main><!-- End #main -->
</x-main>

resources/views/admin/categories/index.blade.php
<x-main>
    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
          <div class="container position-relative">
            <div class="row d-flex justify-content-center">
              <div class="col-lg-6 text-center">
                @if (session('success'))
                <div id="alert" class="alert alert-success">
                  {{ session('success') }}
                </div>
                @endif
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <h2>Categories</h2>
              </div>
            </div>
          </div>
        </div><!-- End Page Header -->

        <section class="sample-page">
          <div class="container" data-aos="fade-up">
            <div class="row mb-2">
                <div class="col-md-3 offset-md-9">
                    <a href="{{ route('admin.categories.create') }}">
                        <button type="button" class="btn btn-sm btn-primary float-right">
                           <i class="fa fa-plus text-white"></i> Add Category
                         </button>
                    </a>
                </div>
            </div>
             <table class="table table-responsive-lg table-responsive-md table-responsive-sm">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $category)
                    <tr>
                        <td>
                            {{ $category->name }}
                        </td>
                        <td>{{ $category->desc }}</td>
                        <td>
                            <a href="{{route('admin.categories.edit', $category->id)}}">
                                <i class="fa fa-edit text-primary"></i>
                            </a>
                            <span>
                                <form action="{{ route('admin.categories.destroy', $category->id) }}" method="POST" class="form-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" name="delete" onclick="
                                        event.preventDefault();
                                        Swal.fire({
                                            title: 'Are you sure?',
                                            text: 'You will not be able to recover this category!',
                                            icon: 'warning',
                                            showCancelButton: true,
                                            confirmButtonText: 'Yes, delete it!',
                                            cancelButtonText: 'No, keep it'
                                        }).then((result) => {
                                            if (result.value) {
                                                this.closest('form').submit();
                                            }
                                        });
                                    ">
                                        <i class="fa fa-trash text-danger"></i>
                                    </button>
                                </form>

                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
             </table>
          </div>
        </section>


      </main><!-- End #main -->
</x-main>